name: lapack
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  complex: ^0.7.2

dev_dependencies:
  lints: ^4.0.0
  path: ^1.9.0
  stack_trace: ^1.11.1
  test: ^1.24.0

topics:
  - lapack
  - blas
  - linear
  - algebra
  - math
  - mathematics
  - matrix
  - vector
  - array
