name: dart_lapack
description: Pure Dart implementation of LAPACK Linear Algebra PACKage
version: 0.1.0
homepage: https://www.lepsch.com/
repository: https://github.com/lepsch/dart_lapack/

environment:
  sdk: ^3.4.3

dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  complex: ^0.7.2

dev_dependencies:
  lints: ^4.0.0
  path: ^1.9.0
  stack_trace: ^1.11.1
  test: ^1.24.0

topics:
  - algebra
  - blas
  - eigenvalues
  - eigenvectors
  - lapack
  - linear
  - linear-algebra
  - linear-equations
  - math
  - mathematics
  - matrix
  - matrix-factorization
  - singular-values
  - svd
  - vector
